Prevent duplicate invitations
bullet-train-co/bullet_train-core pull request #353
Opened 2023-07-18 06:26 UTC by gazayas

Context: https://discord.com/channels/836637622432170028/1130331556137947188

Tests: https://github.com/bullet-train-co/bullet_train/pull/812

As you can see from the tests, we prevent sending invitations to the same email, but we can still use the resend button to send another invitation to the same email.

2023-07-18 15:46 UTC, vfonic requested changes
This fixes the underlying issue only for this particular controller action.

The underlying issue is: user can have only one membership to the same team

I found another way to "exploit" this, without having to write any new code.*

Steps:

1. Send invite to michael@gmail.com (asd@ada-dev.com in screenshot below)
2. Accept invite as michael@gmail.com (asd@ada-dev.com)
3. Send invite to michael@our-big-corp.com (desi@ada-dev.com)
4. Accept invite for michael@our-big-corp.com (desi@ada-dev.com) as michael@gmail.com (asd@ada-dev.com)

Expected:

You see an error saying that you're already a member

Actual:

You now have two memberships connected to the same `User`.

![Screenshot 2023-07-18 at 10 39 50](https://github.com/bullet-train-co/bullet_train-core/assets/67437/1eb4d2b2-4d15-4e74-b844-a64350eae5c8)

This could create permission bugs if we're only checking "first" (which comes) membership (`Membership.find_by(user:, team:)` or similar).


*What I mean by "without having to write any new code" is related to my comment on Discord:

> I just tested it out in rails console:

```ruby
m = Membership.all.sample
newm = m.dup
newm.save # creates new Membership record witht the same [user_id, team_id]
```

> Maybe this issue/bug never happened, but there's nothing preventing it from happening. It could be as simple code as above or it could be a code where someone could have a data migration and/or task assigning memberships to teams or someone might have double clicked on submit button because of slow connection (wouldn't that create two memberships)?

> I dug deeper and it seems like you can create as many invitations as you want for: the same email, the same team, the same role/permissions. These are all the same email addresses in the screenshot. This definitely looks like a bug to me.

2023-08-02 19:39 UTC, jagthedrummer commented
It does seem like there should be database constraints that ensure unique `team_id`/`user_id` combinations on the `memberships` table. And maybe also for the `team_id`/`user_email` combo.

2023-08-11 18:45 UTC, jagthedrummer commented
@gazayas, just curious what you think about the feedback offered above. Would a database constraint be a bad idea? And if we did add one, would it mean that these changes could be simpler?

2023-08-14 07:53 UTC, gazayas commented
@jagthedrummer Definitely not a bad idea, will have to take a second look

2023-08-15 05:46 UTC, gazayas commented
@jagthedrummer I changed some things around to make sure duplicate invitations aren't sent, does this go along the lines of what you were thinking of? Would be glad to to take a closer look if not.

I opened a new joint PR for this one too:
- https://github.com/bullet-train-co/bullet_train/pull/856

2023-08-23 14:57 UTC, jagthedrummer commented
@gazayas, this is looking great! Gonna merge it and release it today in `1.3.12`.

2023-08-23 14:57 UTC, merged

2023-08-25 00:27 UTC, gazayas commented on bullet_train/config/locales/en/invitations.en.yml
> +      duplicate: 'Sorry, a member with the email %{user_email} has already been invited.'
Opened #473 to resolve this.